name: Deploy Backend (Spring Boot)

on:
  workflow_dispatch: # 수동 실행 버튼
  push:
    branches: [ "release/**" ]
    # paths:  <-- 테스트를 위해 주석 처리 유지
    #   - 'snow-on-be/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # (Java 세팅, Maven 빌드 단계 -> Dockerfile이 다 함)

      # 2. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Docker Image 빌드 및 푸시 (여기서 Dockerfile이 실행되면서 Maven 빌드도 같이 됨)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./snow-on-be # Dockerfile이 있는 폴더
          file: ./snow-on-be/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/snow-be:latest

      # 4. EC2 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd snow-project
            sudo docker-compose pull app-be
            sudo docker-compose up -d app-be
            sudo docker image prune -f